/** 独立验证随包报告，不需要93份缓存输入、旧D9副本或任何网络连接。 */
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {validateBundle} from '../src_D10/validate_D10.mjs';
import {toCSV,toChenVerify,sha,buildGroup} from '../src_D10/report_D10.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),read=p=>JSON.parse(readFileSync(resolve(root,p),'utf8'));
const bundle=read('results_D10/核验报告合集_D10.json'),schema=read('schema_D10/核验报告_schema_D10.json');let checks=0;
const check=(name,fn)=>{fn();checks++;console.log('PASS '+name);};
const reject=(name,change,code)=>check(name,()=>{const x=structuredClone(bundle);change(x);const e=validateBundle(x,schema);assert.ok(code?e.some(i=>i.code===code):e.length);});
check('10组报告Schema与引用完整',()=>{assert.equal(bundle.results.length,10);assert.deepEqual(validateBundle(bundle,schema),[]);});
check('精简保留原报告字节',()=>assert.equal(sha(readFileSync(resolve(root,'results_D10/核验报告合集_D10.json'))),read('依赖与来源_D10.json').report_sha256));
reject('缺五段中的计算段拒绝',x=>delete x.results[0].report.calculations);
reject('成员哈希错序拒绝',x=>x.results[0].input_sha256.reverse(),'MEMBER_ORDER');
reject('重复组拒绝',x=>x.results[1].case_id=x.results[0].case_id,'DUPLICATE_GROUP');
reject('跨文件串证据拒绝',x=>x.results[0].report.evidence[0].file_sha256='f'.repeat(64),'CROSS_FILE_EVIDENCE');
reject('归因引用断链拒绝',x=>x.results[0].report.attribution.attributions[0].evidence_ids.push('missing'),'EVIDENCE_REF_MISSING');
reject('差异别名漂移拒绝',x=>x.results[0].diff_list=[],'DIFF_ALIAS_DRIFT');
reject('金额/股数计算结果浮点化拒绝',x=>x.results[0].report.calculations[0].result=8427900);
reject('计算缺依据拒绝',x=>x.results[0].report.calculations[0].evidence_ids=[],'CALC_WITHOUT_BASIS');
reject('unknown不能跨文档计算',x=>{const r=x.results[5];r.diff_list[0].comparison_performed=true;r.report.diffs.items=structuredClone(r.diff_list);},'CROSS_EVENT_COMPARISON');
check('同公司不同事件/扫描第三态保持',()=>{assert.equal(bundle.results[2].report.diffs.relation,'unrelated');assert.equal(bundle.results[5].report.diffs.relation,'unknown');});
check('有据合计精确求和且不分摊',()=>{for(const c of bundle.results[0].report.calculations){assert.equal(c.operands.length,4);assert.equal(c.operands.reduce((n,x)=>n+BigInt(x.value),0n).toString(),c.result);assert.equal(c.details.allocation_performed,false);}});
check('未核实缓存状态不改成true',()=>{for(const r of bundle.results){assert.equal(r.cache.cold_cache_new_call_log,null);assert.equal(r.cache.web_cli_same_result,null);}});
check('CSV可直接从主报告生成',()=>{const x=structuredClone(bundle);x.results[0].case_id='=1+1';assert.ok(toCSV(x).includes("'=1+1"));assert.equal(toCSV(x).trim().split('\r\n').length,11);});
check('陈summary/findings/pairs投影保留',()=>{const p=toChenVerify(bundle);assert.equal(p.pairs.length,10);assert.equal(p.findings.length,35);assert.equal(p.summary.verified_events,0);});
check('缺少D9显式依赖报错而非暗中使用已删文件',()=>assert.throws(()=>buildGroup({}),/D9_ATTRIBUTE_CASE_REQUIRED/));
console.log(JSON.stringify({checks,passed:checks,report_groups:10,scope:'推送版结构/语义检查；不代替模型缓存或实际Web验收'}));
