/** 合成公开开发样例，不使用封存测试。 */
export const field = (raw_value, value, unit = 'text', extra = {}) => ({ raw_value, value, unit, standardized: true, status: 'extracted', provenance: [{ block_id: 'synthetic-b1', source_type: 'paragraph', page: 1, region: null, table_id: null, cell_ref: null, quote: raw_value }], denominator: null, note: null, ...extra });
export const missing = (unit = 'text', status = 'not_mentioned') => ({ raw_value: null, value: null, unit, standardized: false, status, provenance: [], denominator: null, note: null });
const REGISTRY = { pledge: { direction: 'text', pledgor: 'text', pledgee: 'text', pledged_shares_this_time: 'shares', pledged_shares_cumulative: 'shares', pledged_ratio_this_time_of_held: 'percent', pledged_ratio_this_time_of_total: 'percent', pledged_ratio_cumulative_of_held: 'percent', pledged_ratio_cumulative_of_total: 'percent', pledge_amount: 'cny', start_date: 'date', end_date: 'date', purpose: 'text', announcement_date: 'date' }, equity_change: { holder: 'text', direction: 'text', shares_before: 'shares', shares_after: 'shares', ratio_before: 'percent', ratio_after: 'percent', change_shares: 'shares', method: 'text', change_date: 'date_range' }, award_contract: { bidder: 'text', tenderer: 'text', project_name: 'text', bid_amount: 'cny', currency: 'text', tax_included: 'text', duration: 'text', consortium_members: 'text', consortium_shares: 'text', bid_date: 'date', contract_signed: 'text', formal_award_notice_received: 'text', price_adjustment_status: 'text', recognized_revenue: 'cny' } };
export function envelope(type = 'award_contract', sha = 'a') {
  const fields = Object.fromEntries(Object.entries(REGISTRY[type]).map(([k, u]) => [k, missing(u)]));
  if (type === 'award_contract') Object.assign(fields, { bidder: field('甲公司', '甲公司'), tenderer: field('乙公司', '乙公司'), project_name: field('一号项目', '一号项目'), bid_amount: field('人民币100万元', '1000000', 'cny'), currency: field('人民币', 'CNY'), tax_included: field('含税', 'true'), consortium_members: missing('text', 'not_applicable'), consortium_shares: missing('text', 'not_applicable'), bid_date: field('2026年10月3日', '2026-10-03', 'date') });
  if (type === 'pledge') Object.assign(fields, { direction: field('质押', 'pledge'), pledgor: field('甲公司', '甲公司'), pledgee: field('乙银行', '乙银行'), pledged_shares_this_time: field('100万股', '1000000', 'shares'), start_date: field('2026年10月3日', '2026-10-03', 'date'), pledged_ratio_this_time_of_total: field('10%', '10', 'percent', { denominator: 'total_share_capital' }) });
  if (type === 'equity_change') Object.assign(fields, { holder: field('甲公司', '甲公司'), direction: field('增持', 'increase'), shares_before: field('100万股', '1000000', 'shares'), shares_after: field('120万股', '1200000', 'shares'), change_shares: field('20万股', '200000', 'shares'), change_date: field('2026年10月3日', '2026-10-03', 'date_range') });
  return { schema_version: '0.3', run_id: 'synthetic-D7-' + sha, is_mock: true, source: { file_id: 'sha256:' + sha.repeat(64), file_sha256: sha.repeat(64), file_name: `synthetic-${sha}_D7.txt`, parse_meta: { parser_version: 'synthetic', page_count: 1, blocks: null } }, events: [{ event_id: 'E01', event_type: type, fields, extraction_method: 'mock', notes: null }], run_meta: { entry: 'tool', model: null, started_at: '2026-10-03T00:00:00+08:00', duration_ms: 0, code_version: 'synthetic-D7', errors: [] } };
}
export function sample(gold = envelope(), actual = structuredClone(gold), extra = {}) { return { case_id: 'case-1', cohort: 'core', gold, actual, execution: actual ? 'completed' : 'failed', format_valid: actual ? true : false, ...extra }; }
