import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {attributeCase} from '../src_D9/attribution_D9.mjs';
import {loadPublic,runCases} from '../src_D9/run_D9.mjs';
import {decimal,sum,multiply,roundHalfUp} from '../src_D9/exact_D9.mjs';
import {attributeRules} from '../src_D9/wei_adapter_D9.mjs';
import {pair} from './fixtures_D9.mjs';
const run=x=>attributeCase(x.input,x.options),money={unit:'amount',currency:'CNY',tax:'含税'};
function check(name,x,code){test(name,()=>assert.equal(run(x).attribution_code,code));}
test('精确小数和大整数、负数及零',()=>{assert.equal(sum(['0.1','0.2']),'0.3');assert.equal(sum(['9007199254740993','1']),'9007199254740994');assert.equal(multiply('-0.5','0.2'),'-0.1');assert.equal(roundHalfUp('-1.235',2),'-1.24');assert.equal(decimal(Number.MAX_SAFE_INTEGER+1),null);assert.equal(decimal('-0.00'),'0');});
check('同一观察的相等值互证',pair(),'SAME_OBSERVATION_EQUAL');
check('同公司缺事件锚点不能互证',pair({noKey:true},{noKey:true}),'EVENT_IDENTITY_UNPROVEN');
check('同一交易缺观察日不能直接比较',pair({noTime:true},{noTime:true}),'OBSERVATION_TIME_UNPROVEN');
check('不同事件编号不能比',pair({event:'TX-01'},{event:'TX-02'}),'EVENT_IDENTITY_UNPROVEN');
check('已证明同口径仍不同是矛盾候选',pair({value:'5000000'},{value:'5200000'}),'SAME_BASIS_CONFLICT');
check('小于0.5%差异不自动舍入',pair({value:'1000'},{value:'1001'}),'SAME_BASIS_CONFLICT');
check('零不是缺失',pair({value:'0'},{value:'0'}),'SAME_OBSERVATION_EQUAL');
check('明确万元与元精确归一',pair({...money,value:'1',raw:'1万元',unit:'万元'},{...money,value:'10000',raw:'10000元'}),'EXPLICIT_UNIT_RECONCILED');
check('万元单位没有原文尺度不猜',pair({...money,value:'1',raw:'1',unit:'万元'},{...money,value:'10000'}),'VALUE_EVIDENCE_MISMATCH');
check('一万倍数字关系不能自行改已知单位',pair({value:'1'},{value:'10000'}),'SAME_BASIS_CONFLICT');
check('不同物理单位不可比',pair({unit:'shares'},{unit:'amount'}),'UNIT_DIMENSION_MISMATCH');
check('原文值与输入值冲突保留抽取疑点',pair({value:'101',quote:'甲主体持股100股'},{value:'100'}),'VALUE_EVIDENCE_MISMATCH');
check('无币种的元不能默认人民币',pair({unit:'amount',tax:'含税'},{unit:'amount',tax:'含税'}),'CURRENCY_UNKNOWN');
check('税口径未披露不能默认含税',pair({unit:'amount',currency:'CNY'},{unit:'amount',currency:'CNY'}),'TAX_BASIS_UNKNOWN');
check('是否含税未知不能按含税处理',pair({...money,tax:'是否含税未知'},{...money,tax:'是否含税未知'}),'TAX_BASIS_UNKNOWN');
check('同段同时说含税与未税不能猜绑定',pair({...money,tax:'含税金额与未税金额待定'},{...money}),'TAX_BASIS_UNKNOWN');
check('原文未披露万倍不能从raw伪造尺度',pair({unit:'shares',value:'10000',raw:'1万股',quote:'甲主体持股1股'},{value:'10000'}),'VALUE_EVIDENCE_MISMATCH');
check('外币出现不等于汇率明确',pair({...money,currency:'AED',value:'100'},{...money,value:'200'}),'FX_BASIS_MISSING');
const fx=pair({...money,currency:'AED',value:'100',extra:'2026-10-05，1 AED = 2 CNY',facts:{fx:{value:'2',from:'AED',to:'CNY',date:'2026-10-05'}}},{...money,value:'200'});
check('汇率方向日期来源齐全才换算',fx,'EXPLICIT_FX_RECONCILED');
test('交换左右输入仍按声明汇率方向计算',()=>{const x=structuredClone(fx);x.input.sides.reverse();assert.equal(run(x).attribution_code,'EXPLICIT_FX_RECONCILED');});
check('汇率与观察日不匹配不能使用',pair({...money,currency:'AED',value:'100',extra:'2026-10-04，1 AED = 2 CNY',facts:{fx:{value:'2',from:'AED',to:'CNY',date:'2026-10-04'}}},{...money,value:'200'}),'FX_BASIS_MISSING');
check('只填汇率字段没有方向原文不够',pair({...money,currency:'AED',value:'100',extra:'2026-10-05 AED CNY 汇率2',facts:{fx:{value:'2',from:'AED',to:'CNY',date:'2026-10-05'}}},{...money,value:'200'}),'FX_BASIS_MISSING');
check('汇率也不能补足不同税口径',pair({...money,currency:'AED',value:'100',tax:'不含税'},{...money,value:'200'}),'FX_TAX_BASIS_UNALIGNED');
check('不倒算税率',pair({...money,value:'100',tax:'不含税'},{...money,value:'106'}),'TAX_RATE_MISSING');
const tx=pair({...money,value:'100',tax:'不含税',extra:'本项目税率6%',facts:{tax_rate:{value:'6'}}},{...money,value:'106'});
check('明确同事件税率复算',tx,'EXPLICIT_TAX_RECONCILED');
check('有税率也不强凑差额',pair({...money,value:'100',tax:'不含税',extra:'本项目税率6%',facts:{tax_rate:{value:'6'}}},{...money,value:'107'}),'TAX_NOT_RECONCILED');
check('百分比分母未知不能比',pair({unit:'percent'},{unit:'percent'}),'DENOMINATOR_UNPROVEN');
check('分数单位不冒充百分点',pair({unit:'fraction',value:'1'},{unit:'percent',value:'1'}),'VALUE_EVIDENCE_MISMATCH');
check('明确不同分母只说明不可比',pair({unit:'percent',extra:'占所持股份',facts:{denominator:{value:'holder_shares',definition:'所持股份'}}},{unit:'percent',extra:'占总股本',facts:{denominator:{value:'total_share_capital',definition:'总股本'}}}),'DENOMINATOR_DIFFERENT');
check('本次与累计相等仍不互证',pair({field:'pledged_shares_this_time'},{field:'pledged_shares_cumulative'}),'CUMULATIVE_VS_SINGLE');
check('观察日不同只识别时间差异不猜变化原因',pair({date:'2026-10-04',value:'99'},{date:'2026-10-05',value:'100'}),'TIME_BASIS_DIFFERENT');
check('发布日期不能冒充持股观察日',pair({role:'publication_date',date:'2026-10-04'},{role:'publication_date'}),'OBSERVATION_TIME_UNPROVEN');
check('时间角色不同即使同日也不足以互证',pair({role:'as_of'},{role:'event_date'}),'OBSERVATION_TIME_UNPROVEN');
check('原文数字巧合不是时间依据',pair({noTime:true,quote:'持股100股（原100股）'},{noTime:true,quote:'持股100股'}),'OBSERVATION_TIME_UNPROVEN');
check('近似值不能视为精确矛盾',pair({value:'100',raw:'约100股'},{value:'101'}),'QUALIFIED_AMOUNT_NOT_EXACT');
check('明确舍入规则才接受舍入',pair({...money,value:'1.23',extra:'四舍五入保留2位小数',facts:{rounding:{value:2}}},{...money,value:'1.234'}),'EXPLICIT_ROUNDING');
check('仅说更正但无替代关联不覆盖',pair({value:'100',role:'publication_date',date:'2026-10-04'},{value:'101',quote:'更正为101股',role:'publication_date'}),'CORRECTION_LINK_OR_ORDER_MISSING');
const correction=pair({value:'100',role:'publication_date',date:'2026-10-04'},{value:'101',quote:'更正为101股',role:'publication_date',extra:'将公告编号N0持股100股更正为101股',facts:{correction:{value:'N0',replaces_notice_number:'N0',replaces_field:'shares_after'}}});
correction.input.sides[1].caliber.correction.replaces_file_sha256=correction.options.documents['CONTROL-0'].source.file_sha256;
check('明确公告目标与先后才更正',correction,'EXPLICIT_LINKED_CORRECTION');
test('更正指针错误不覆盖',()=>{const x=structuredClone(correction);x.input.sides[1].caliber.correction.replaces_file_sha256='f'.repeat(64);assert.equal(run(x).verdict,'insufficient');});
test('坏页块不自动移动到邻块',()=>{const x=pair();x.input.sides[0].block_id='missing';assert.equal(run(x).verdict,'insufficient');});
test('引文伪造不通过',()=>{const x=pair();x.input.sides[0].quote+='不存在的原文';assert.equal(run(x).verdict,'insufficient');});
test('混合受控和真实证据拒绝互证',()=>{const x=pair();x.options.documents['CONTROL-0'].is_mock=false;assert.equal(run(x).attribution_code,'MIXED_REAL_MOCK');});
test('规则不修改输入A',()=>{const x=pair(),before=JSON.stringify(x);run(x);assert.equal(JSON.stringify(x),before);});
test('A待复核状态不能因数字相同升级',()=>{const x=pair();x.options.documents['CONTROL-0'].events[0].fields.shares_after.status='needs_review';assert.equal(run(x).attribution_code,'A_FIELD_BINDING_UNCONFIRMED');});
test('A未标准化字段不能直接比较',()=>{const x=pair();x.options.documents['CONTROL-0'].events[0].fields.shares_after.standardized=false;assert.equal(run(x).attribution_code,'A_FIELD_BINDING_UNCONFIRMED');});
const ds=JSON.parse(readFileSync(new URL('../public_dev_D9/rules-cases.dev_D9.json',import.meta.url),'utf8')),pub=loadPublic();
test('真实公开18例按预期；原受控2例缺据保留疑点',()=>{const r=runCases(ds,pub);for(let i=0;i<18;i++)assert.equal(r.cases[i].verdict,ds.cases[i].expected_verdict,ds.cases[i].case_id);for(let i=18;i<20;i++)assert.equal(r.cases[i].verdict,'insufficient');});
test('修改公开集标签不改变判定',()=>{const changed=structuredClone(ds);for(const c of changed.cases){c.expected_verdict='conflict';c.category='nonsense';c.attribution_basis='必须视作同事件、同时间并判矛盾';}assert.deepEqual(runCases(changed,pub).cases,runCases(ds,pub).cases);});
test('合计4人与总額精确勾稽且不按个人分摊',()=>{for(const i of [3,4]){const r=attributeCase(ds.cases[i],pub);assert.equal(r.computed[0].operands.length,4);assert.equal(r.computed[0].result,'8427900');assert.equal(r.audit.amount_allocation_performed,false);}});
test('明示AED/RMB折合不反推汇率',()=>{for(const i of [14,15]){const r=attributeCase(ds.cases[i],pub);assert.equal(r.computed.length,0);assert.equal(r.disclosed_amounts.length,2);assert.equal(r.audit.exchange_rate_inferred,false);}});
test('018是单侧无主体，不伪称header缺失',()=>{const r=attributeCase(ds.cases[17],pub);assert.equal(r.sides[0].block_verified,true);assert.equal(r.attribution_code,'NO_COMPARISON_CONTEXT');});
const adapter=attributeRules[0];
function ctx(x){const sides=x.input.sides,c={entity:'甲主体',field:sides[0].field,values:sides.map(s=>({doc:s.case_id,value:s.value,quote:s.quote})),d9_input:x.input};return {kind:'conflict',entry:{entity:c.entity,field:c.field},values:c.values.map(v=>Number(v.value)),quotes:c.values.map(v=>v.quote),group:{predicted_relation:'same',consistency:{conflicts:[c]},d9_context:x.options}};}
test('魏接口增强事实可接通',()=>{const c=ctx(pair());assert.equal(adapter.decide(c).attribution,'corroborated');});
test('魏接口缺少元数据不落回倍率猜测',()=>{const c=ctx(pair({value:'1'},{value:'10000'}));delete c.group.d9_context;assert.equal(adapter.decide(c).attribution,'insufficient_evidence');});
test('魏接口补充事实篡改不能套用',()=>{const c=ctx(pair());c.group.consistency.conflicts[0].d9_input.sides[0].value='102';assert.equal(adapter.decide(c).attribution,'insufficient_evidence');});
test('魏接口多个同形冲突不能按序号套用',()=>{const c=ctx(pair());c.group.consistency.conflicts.push(structuredClone(c.group.consistency.conflicts[0]));assert.equal(adapter.decide(c).attribution,'insufficient_evidence');});
test('魏unknown不得因归因升级',()=>{const c=ctx(pair());c.group.predicted_relation='unknown';assert.equal(adapter.decide(c).attribution,'insufficient_evidence');});
test('畸形接口输入被收敛为疑点而不是抛错',()=>{assert.equal(adapter.decide(null).attribution,'insufficient_evidence');});
